### ISSUE TITLE
Better LOGO

### ISSUE THREAD

**Issue by aeilot** [ChungZH/notepanda#15]
I saw your project on GitHub and I truly wanted to help. 

I would love to help to improve your logo.

**Comment by aeilot** [comment]
Styles could be considered:
* Futuristic Design
* Material Design

**Comment by zirnc** [comment]
其实不用这样的...我的小玩具而已嘛，不是什么大项目 :joy: 我还是喜欢自己画的，对我来说更有意义。
但是谢谢你啦！

**Comment by zirnc** [comment]
a14884d
