### ISSUE TITLE
Running the notepanda.exe file prompts an error

### ISSUE THREAD

**Issue by hajing** [ChungZH/notepanda#29]
Running the notepanda.exe file prompts an error: VCRUNTIME140_1.dll could not be found and execution cannot be continued.

**Comment by zirnc** [comment]
Cannot reproduce, please provide more information, such as system version number, Notepanda version number (available on the AboutWindow).

**Comment by zirnc** [comment]
Also, are you using the NSIS installer(.exe) or 7z?
