### ISSUE TITLE
Misuse of license notice

### ISSUE THREAD

**Issue by ghost** [ChungZH/notepanda#44]
The following license notice is used throughout the project repository:

> Copyright (c) 2020 ChungZH. All Rights Reserved.

Generally, this is a valid license notice. However, by "all rights reserved", all rights provided by the copyright law is reserved to yourself, including most of the rights granted by the MIT License, which renders the latter invalid.

To properly license the project with MIT License, the "all rights reserved" term should be removed from the license notice. On the other hand, if "all rights reserved" is exactly what you want, it is recommended to remove the MIT license, as it would bring you trouble when it comes to jurisdiction.

**Comment by zirnc** [comment]
Thanks.
