### ISSUE TITLE
A better editor component which should be considered

### ISSUE THREAD

**Issue by aeilot** [ChungZH/notepanda#5]
**Scintilla** which is used on Notepad++ is a wonderful source code editing component.
[Its website](https://www.scintilla.org)
[GitHub Mirror](https://github.com/mirror/scintilla)
There's an example: [martinrotter/textosaurus](https://github.com/martinrotter/textosaurus)

Scintilla is capable with Qt and GTK, so it might be easy to use in your wonderful project. It brings powerful features and extremely awesome experiences which can make this project better.

**Comment by zirnc** [comment]
Thank you. But now I want to be familiar with Qt. Maybe I will use Scintilla in the future.
